version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5037:80"
      - "7266:443" # redoc, scalar (HTTPS)
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ConnectionStrings__DefaultConnection=Host=db;Database=minhacarteira;Username=postgres;Password=postgres
      - Jwt__Key=your_super_secret_key_here_min_32_chars
      - Jwt__Issuer=minhacarteira
      - Jwt__Audience=minhacarteira
    volumes:
      - ./aspnetapp.pfx:/https/aspnetapp.pfx:ro
    depends_on:
      - db
    networks:
      - minhacarteira-network
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=minhacarteira
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minhacarteira-network
    restart: unless-stopped

networks:
  minhacarteira-network:
    driver: bridge

volumes:
  postgres_data:
