version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=minhacarteira;Username=postgres;Password=postgres
    depends_on:
      - db
    networks:
      - minhacarteira-network
    restart: unless-stopped

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=minhacarteira
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minhacarteira-network
    restart: unless-stopped

networks:
  minhacarteira-network:
    driver: bridge

volumes:
  postgres_data:
